# URL para se conectar no Eureka Server.
eureka.client.serviceUrl.defaultZone = http://localhost:7875/eureka

# Id da instância
eureka.instance.instance-id=${spring.application.name}

eureka.instance.hostname=localhost
