spring.application.name=ms-autenticacao

server.port=7889

spring.datasource.url=jdbc:postgresql://localhost:6589/autenticacao

spring.datasource.username=admin

spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

logging.level.com.thiagoLima.ms_autenticacao=DEBUG
logging.level.org.springframework.security=DEBUG