server.port=7878

spring.datasource.url=jdbc:postgresql://localhost:6589/pessoas

# Nome do usuário de conexão com o banco
spring.datasource.username=admin
# Senha de conexão com o banco
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update