# Porta do servidor
server.port=7879

# Caminho do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:6589/mercadinho

# Nome do usuário de conexão com o banco
spring.datasource.username=admin
# Senha de conexão com o banco
spring.datasource.password=admin

# Nome do driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao para indicar o hibernate para gerar atualizacoes automaticas constantemente no schema
spring.jpa.hibernate.ddl-auto=update