spring.application.name=config-server
server.port=7880
# como as informações serão obtidas
spring.profiles.active=native
# caminho de onde se deve pegar as informações
spring.cloud.config.server.native.search-locations=/home/dev/Documentos/estudos_spring/workspace/configs
